version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.1
    - 12.7.2
    - 12.8.1
    - 12.8.3
    - 13.0.16
    - 13.0.7
    - 13.1.1
    - 13.1.2
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: styled-components
    versions:
    - 5.2.1
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.1
    - 2.12.0
    - 2.9.3
  - dependency-name: protobuf
    versions:
    - 3.14.0
    - 3.15.1
    - 3.15.6
    - 3.15.7
  - dependency-name: google-cloud-storage
    versions:
    - 1.35.0
    - 1.35.1
    - 1.36.0
    - 1.36.2
    - 1.37.0
    - 1.37.1
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.2
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
  - dependency-name: markdown
    versions:
    - 3.3.3
